# The network interface that should be used for load balancing
listenInterface: eth1
# The tcp port to listen on
tcp_port: 80
# List of backend mac addresses to forward packets to
backends: 
  - "ca:fe:ba:be:47:11"
  - "ca:fe:ba:be:47:12"